#!/usr/bin/env python

import imdb
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

# create objects to access SQL database with IMDb's information
access = imdb.IMDb();

# search for title and output results
results = access.search_movie(sys.argv[1])
results = [x for x in results if x["kind"] == "movie"]

for movie in results:
    if "year" in movie.keys():
        year = movie["year"]
    else:
        year = "Unknown Year"

    print movie.movieID
    print movie["title"]
    print year
