#!/usr/bin/env python

import sys
import imdb

# create object to access SQL database with IMDb's information
access = imdb.IMDb('sql', uri='mysql://root:jdieks,zla42@localhost:3306/imdb')

# search for title and output results
results = access.search_movie(sys.argv[1])
for movie in results:
    print movie["long imdb title"]
    print movie.movieID
